- name: Setting storage related tasks
  hosts: all
  tasks:
    - name: OS provision
      package:
        name: ntfs-3g, ntfsprogs, samba, samba-client, samba-common

    - name: NTFS is configured and mounted
      mount: 
        path: /mnt/ntfs
        src: /dev/sda2
        fstype: ntfs-3g
        state: mounted
